version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build step...
  build:
    commands:
      - echo "Hello world"
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
